#1. Import the NUMPY package under the name np.


In [1]:
import numpy as np

In [2]:
#2 Print the NUMPY version and the configuration.
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/katiahernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/katiahernandez/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/katiahernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/katiahernandez/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/katiahernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/katiahernandez/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/katiahernandez/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/katiahernandez/opt/anaconda3/inc

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. 
#How many ways can you find?


In [4]:
#1) random de flotantes 
a = np.random.random((2,3,5))
print(a)

[[[0.43781872 0.91891541 0.9195965  0.9723995  0.57015458]
  [0.80909802 0.6145649  0.5950401  0.55052922 0.10084693]
  [0.20146299 0.42454451 0.58370606 0.11051345 0.20130278]]

 [[0.0232622  0.28397695 0.59154202 0.41574285 0.81865561]
  [0.13506442 0.83783085 0.44549155 0.7160454  0.38397941]
  [0.93948895 0.38028427 0.27798533 0.88667407 0.81044128]]]


In [5]:
#2) flotantes de distribución estándar normal 
a = np.random.rand(2,3,5)
print(a)

[[[0.61012608 0.03172831 0.60475481 0.56562241 0.55894995]
  [0.80273284 0.18017594 0.66009251 0.88805807 0.62756779]
  [0.61260411 0.40076805 0.55305643 0.79052092 0.2850397 ]]

 [[0.02951182 0.81311737 0.68319725 0.39057919 0.23299573]
  [0.92742678 0.50088952 0.79855415 0.89020049 0.82161606]
  [0.42860503 0.34087354 0.69403303 0.75529106 0.3006247 ]]]


In [18]:
#3) números enteros 
a = np.random.randint(100, size=(2,3,5))
print(a)

[[[78 41 13 26 56]
  [13 15 79 81 38]
  [26  3 92 73 47]]

 [[81  1 95 43 63]
  [57 37 75 84 13]
  [28 13 24 91  3]]]


In [19]:
#5. Create a 5x3x2 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,3,2))

print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [20]:
#7. Do a and b have the same size? How do you prove that in Python code?
# Si son del mismo tamaño 
print(b.size)
print(a.size)

30
30


In [21]:
#8. Are you able to add a and b? Why or why not?
#No se puede sumar las matrices, no tienen la misma forma
print(np.add(a,b))

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 

In [22]:

#9. Transpose b so that it has the same structure of a 
#(i.e. become a 2x3x5 array).
# Assign the transposed array to varialbe"c".

c =np.transpose(b)
print(c.shape)
print(a.shape)


(2, 3, 5)
(2, 3, 5)


In [23]:
#10. Try to add a and c. Now it should work. 
#Assign the sum to varialbe "d". But why does it work now?

#Ahora tiene la misma forma (2,3,5)

d = np.add(a,c)

In [24]:
#11. Print a and d. Notice the difference and relation 
#of the two array in terms of the values? Explain.


In [25]:
print(a)

[[[78 41 13 26 56]
  [13 15 79 81 38]
  [26  3 92 73 47]]

 [[81  1 95 43 63]
  [57 37 75 84 13]
  [28 13 24 91  3]]]


In [26]:
print(d)

[[[79. 42. 14. 27. 57.]
  [14. 16. 80. 82. 39.]
  [27.  4. 93. 74. 48.]]

 [[82.  2. 96. 44. 64.]
  [58. 38. 76. 85. 14.]
  [29. 14. 25. 92.  4.]]]


In [27]:
# La matriz d es mayor que la a por 1 unidad en todos sus valores 

In [28]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)
print(e)

[[[78. 41. 13. 26. 56.]
  [13. 15. 79. 81. 38.]
  [26.  3. 92. 73. 47.]]

 [[81.  1. 95. 43. 63.]
  [57. 37. 75. 84. 13.]
  [28. 13. 24. 91.  3.]]]


In [29]:
#13. Does e equal to a? Why or why not?
#Son los mismo valores, solamente multiplicamos a los valores de "a"x1

In [30]:
print(a)

[[[78 41 13 26 56]
  [13 15 79 81 38]
  [26  3 92 73 47]]

 [[81  1 95 43 63]
  [57 37 75 84 13]
  [28 13 24 91  3]]]


In [31]:
#14. Identify the max, min, and mean values in d.
#Assign those values to variables "d_max", 
#"d_min", and "d_mean"

In [32]:
d_max=np.max(d)
print(d_max)

96.0


In [33]:
d_min =np.min(d)
print(d_min)

2.0


In [34]:
d_mean =np.mean(d)
print(d_mean)

47.3


In [35]:
#15. Now we want to label the values in d.
#First create an empty array "f" with the same shape 
#(i.e. 2x3x5) as d using `np.empty`

In [36]:
f = np.empty([2,3,5])
print(f)

[[[78. 41. 13. 26. 56.]
  [13. 15. 79. 81. 38.]
  [26.  3. 92. 73. 47.]]

 [[81.  1. 95. 43. 63.]
  [57. 37. 75. 84. 13.]
  [28. 13. 24. 91.  3.]]]


In [37]:
#16. Populate the values in f. #
#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.




In [38]:
f = np.empty([2,3,5])
print(f)

[[[78. 41. 13. 26. 56.]
  [13. 15. 79. 81. 38.]
  [26.  3. 92. 73. 47.]]

 [[81.  1. 95. 43. 63.]
  [57. 37. 75. 84. 13.]
  [28. 13. 24. 91.  3.]]]


In [55]:
d_max=np.max(d)
d_mean=np.mean(d)
d_min=np.min(d)
print(d_max)
print(d_mean)
print(d_min)

96.0
47.3
2.0


In [63]:
# Para agregar valores a un array vacío se usa  range() 


#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.


#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.




for i in range(2):
    for x in range(3):
        for y in range(5) :
            if d_min<d[i][x][y]<d_mean:
                f[i][x][y]=25
            elif d_mean<d[i][x][y]<d_max: 
                f[i][x][y] = 50    
            elif d[i][x][y] == d_mean: 
                f[i][x][y] = 50
            elif d[i][x][y] == d_min:
                f[i][x][y] = 0
            elif d[i][x][y] == d_max:
                f[i][x][y] = 100
            

                # remplazae elemento[i][x][elemento] in f
                
                
               

In [64]:
#17. Print d and f. Do you have your expected f? Yes :)
print(f)

[[[ 50.  25.  25.  25.  50.]
  [ 25.  25.  50.  50.  25.]
  [ 25.  25.  50.  50.  50.]]

 [[ 50.   0. 100.  25.  50.]
  [ 50.  25.  50.  50.  25.]
  [ 25.  25.  25.  50.  25.]]]


In [89]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:

ff = []
    
for i in range(2):
    for x in range(3):
        for y in range(5) :
            if d_min<d[i][x][y]<d_mean:
                ff.append('A')
            elif d_mean<d[i][x][y]<d_max: 
                ff.append('B')   
            elif d[i][x][y] == d_mean: 
                ff.append('C')
            elif d[i][x][y] == d_min:
                ff.append('D')
            elif d[i][x][y] == d_max:
                ff.append('E')

In [93]:
#Solo pude utilizando numpy 
abc = np.array(ff)
print(abc)


['B' 'A' 'A' 'A' 'B' 'A' 'A' 'B' 'B' 'A' 'A' 'A' 'B' 'B' 'B' 'B' 'D' 'E'
 'A' 'B' 'B' 'A' 'B' 'B' 'A' 'A' 'A' 'A' 'B' 'A']


In [94]:
np.reshape(abc, (2,3,5))

array([[['B', 'A', 'A', 'A', 'B'],
        ['A', 'A', 'B', 'B', 'A'],
        ['A', 'A', 'B', 'B', 'B']],

       [['B', 'D', 'E', 'A', 'B'],
        ['B', 'A', 'B', 'B', 'A'],
        ['A', 'A', 'A', 'B', 'A']]], dtype='<U1')